version: '3.8'

services:
  supermock-ai-interview:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: supermock-ai-interview
    restart: unless-stopped
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - NODE_ENV=production
    networks:
      - supermock-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  supermock-ai-interview-staging:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: supermock-ai-interview-staging
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - NODE_ENV=staging
    networks:
      - supermock-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  supermock-network:
    driver: bridge
