name: Deploy to Staging

on:
  push:
    branches: [ develop, staging ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 8
        
    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
        
    - name: Setup pnpm cache
      uses: actions/cache@v4
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
          
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      
    - name: Run linting
      run: pnpm run lint
      
    - name: Build application
      run: pnpm run build
      
    - name: Deploy to staging server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.STAGING_HOST }}
        username: ${{ secrets.STAGING_USER }}
        key: ${{ secrets.STAGING_SSH_KEY }}
        port: ${{ secrets.STAGING_PORT }}
        script: |
          # Создаем директорию для staging
          mkdir -p /var/www/supermock-ai-interview-staging
          
          # Останавливаем текущий контейнер если он запущен
          docker stop supermock-ai-interview-staging || true
          docker rm supermock-ai-interview-staging || true
          
          # Удаляем старый образ
          docker rmi supermock-ai-interview-staging:latest || true
          
          # Переходим в директорию проекта
          cd /var/www/supermock-ai-interview-staging
          
          # Очищаем старые файлы
          rm -rf *
          
    - name: Upload files to staging server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.STAGING_HOST }}
        username: ${{ secrets.STAGING_USER }}
        key: ${{ secrets.STAGING_SSH_KEY }}
        port: ${{ secrets.STAGING_PORT }}
        source: "."
        target: "/var/www/supermock-ai-interview-staging"
        strip_components: 0
        
    - name: Build and start staging container
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.STAGING_HOST }}
        username: ${{ secrets.STAGING_USER }}
        key: ${{ secrets.STAGING_SSH_KEY }}
        port: ${{ secrets.STAGING_PORT }}
        script: |
          cd /var/www/supermock-ai-interview-staging
          
          # Собираем Docker образ для staging
          docker build -t supermock-ai-interview-staging:latest .
          
          # Запускаем контейнер на порту 8080
          docker run -d \
            --name supermock-ai-interview-staging \
            --restart unless-stopped \
            -p 8080:80 \
            supermock-ai-interview-staging:latest
            
          # Очищаем неиспользуемые образы
          docker image prune -f
          
    - name: Staging health check
      run: |
        sleep 10
        curl -f http://${{ secrets.STAGING_HOST }}:8080 || exit 1
        
    - name: Comment PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '🚀 Staging deployment completed! You can test your changes at: http://${{ secrets.STAGING_HOST }}:8080'
          })
