name: Test GitHub Secrets

on:
  workflow_dispatch:

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Debug Secrets
      run: |
        echo "Testing GitHub Secrets..."
        echo "SERVER_HOST: ${{ secrets.SERVER_HOST }}"
        echo "SERVER_USER: ${{ secrets.SERVER_USER }}"
        echo "SERVER_PORT: ${{ secrets.SERVER_PORT }}"
        echo "SERVER_SSH_KEY exists: ${{ secrets.SERVER_SSH_KEY != '' }}"
        
        if [ -z "${{ secrets.SERVER_HOST }}" ]; then
          echo "❌ SERVER_HOST is empty"
          exit 1
        fi
        
        if [ -z "${{ secrets.SERVER_USER }}" ]; then
          echo "❌ SERVER_USER is empty"
          exit 1
        fi
        
        if [ -z "${{ secrets.SERVER_PORT }}" ]; then
          echo "❌ SERVER_PORT is empty"
          exit 1
        fi
        
        if [ -z "${{ secrets.SERVER_SSH_KEY }}" ]; then
          echo "❌ SERVER_SSH_KEY is empty"
          exit 1
        fi
        
        echo "✅ All secrets are configured!"
        
    - name: Test SSH Connection
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          echo "SSH connection successful!"
          echo "Server: $(hostname)"
          echo "Date: $(date)"
          echo "Docker containers:"
          docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"
